#! /bin/sh

echo "Going to update conda environment test=cubeviz-conda"

set -eu

conda_env=`conda env list | grep '*' | cut -d\  -f1`
min_conda_version="4.4"

if [ "$conda_env" != "test-cubeviz-conda" ]; then
    echo "Must be in the test-cubeviz-conda conda environment"
    exit 1
fi

# Grab the script:
echo "Downloading the update script"
output_file=`mktemp`
wget -O - --no-check-certificate https://raw.githubusercontent.com/brechmos-stsci/cubeviz/tester-script/scripts/update_cubeviz_test_env_pip > $output_file

echo "Running the update script"
`sh $output`
