#! /bin/sh

echo "Going to update conda environment test-cubeviz-conda"

set -eu

conda_env=`conda env list | grep '*' | cut -d\  -f1`
min_conda_version="4.4"
download_location="https://raw.githubusercontent.com/spacetelescope/cubeviz/master/cubeviz/misc/update_cubeviz_test_env_pip"

if [ "$conda_env" != "test-cubeviz-conda" ]; then
    echo "Must be in the test-cubeviz-conda conda environment"
    exit 1
fi

# Grab the script:
echo "Downloading the update script"
output_file=`mktemp`


wget=`which wget`
curl=`which curl`

if [ ! -z "$wget" ]; then
    wget -O $output_file --no-check-certificate $download_location
elif [ ! -z "$curl" ]; then
    curl -o $output_file $download_location
else
    echo "Need at least one of wget or curl"
fi

if [ ! -z "$wget" ] || [ ! -z "$curl" ]; then
    echo "Running the update script $output_file"
    sh $output_file
fi
